##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile
##


SRC	=	z.c

NAME	=	z

OBJ	=	$(SRC:.c=.o)

all:
	gcc $(SRC) -o $(NAME)
clean:
	rm -rf $(OBJ)

fclean:
	rm -rf $(OBJ)
	rm -rf $(NAME)

re:
	rm -rf $(OBJ)
	rm -rf $(NAME)
	gcc $(SRC) -o $(NAME)
