##
## EPITECH PROJECT, 2019
## Day06
## File description:
## Makefile
##

SRC	=	my_convert_temp.cpp

EXEC	=	my_convert_temp

OBJ	=	$(SRC:.cpp=.o)

all:
	g++ -o $(EXEC) $(SRC)

clean:
	rm -rf $(OBJ)

fclean:	clean

re:	fclean all
